### ISSUE TITLE
All Kafka CLI commands fail if JDK not installed

### ISSUE THREAD

**Issue by keithchambers** [mesosphere/dcos-kafka#8]
Kafka CLI fails with the following error on fresh install of OSX (and perhaps other operating systems):
```
dcos kafka add 0..2
Exception in thread "main" java.lang.UnsupportedClassVersionError: ly/stealth/mesos/kafka/Cli : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

The solution is to install the Java JDK available at: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

It needs to be very clear to users that they must have the JDK installed for the Kafka CLI to work.

**Comment by jbomengo** [comment]
I have JDK installed for Windows and DCOS CLI is not seeing the dependencies required.
